---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: algogenerator-deployment
  namespace: stocks
  labels:
    app: algogeneratorxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algogeneratorxx
  template:
    metadata:
      labels:
        app: algogeneratorxx
    spec:
      containers:
        - name: algogeneratorxx
          image: rowanf/algogenerator:1
          ports:
            - containerPort: 8004
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: spring-dbconfig
---


