apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{name}}-deployment
  namespace: stocks
  labels:
    app: {{name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{name}}
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      containers:
        - name: {{name}}
          image: {{image_name}}
          ports:
            - containerPort: {{portno}}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: spring-dbconfig
            - configMapRef:
                name: email
            - secretRef:
                name: secretpostgress


